version: '3.8'

services:
  app:
    build: .
    container_name: ci3_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    container_name: ci3_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cbt25
      MYSQL_USER: cbt
      MYSQL_PASSWORD: smktkjTH46
    ports:
      - "3314:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
